version: "3.5"
services:
  app_a:
    image: node:8.11.3-alpine
    working_dir: /app/examples/application
    entrypoint: ["npm", "start"]
    environment:
      - PORT=8084
      - SVC_NAME=app_a
      - SVC_OTHER_NAME=app_b
      - SVC_OTHER_URL=http://app_b:8085
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    ports:
      - "8084:8084"
    volumes:
      - "../../:/app:Z"
    depends_on:
      - fluentd
      - zipkin
  app_b:
    image: node:8.11.3-alpine
    working_dir: /app/examples/application
    entrypoint: ["npm", "start"]
    environment:
      - PORT=8085
      - SVC_NAME=app_b
      - SVC_OTHER_NAME=app_a
      - SVC_OTHER_URL=http://app_a:8084
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    ports:
      - "8085:8085"
    volumes:
      - "../../:/app:Z"
    depends_on:
      - fluentd
      - zipkin
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
  fluentd:
    image: govtechsg/fluentd-elasticsearch:latest
    entrypoint: ["fluentd", "-c", "/etc/fluent/fluent.conf"]
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./data/fluentd.d/fluent.conf:/etc/fluent/fluent.conf"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    ports:
      - "5601:5601"
    volumes:
      - "./data/kibana.d/kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      - "elasticsearch"
  prometheus:
    image: prom/prometheus:v2.3.2
    ports:
      - "9090:9090"
    user: "1000"
    volumes:
      - "./data/prometheus:/prometheus:Z"
      - "./data/prometheus.d/prometheus.yml:/etc/prometheus/prometheus.yml:Z"
  zipkin:
    image: openzipkin/zipkin:2.10.2
    ports:
      - "9411:9411"